FROM python:3.8-slim-buster 

# RUN apt update && apt upgrade -y
WORKDIR /app
COPY app.py .
COPY models.py .
COPY requirements.txt .
COPY wsgi.py .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["gunicorn","--bind","0.0.0.0:5000","wsgi:app"]